### ISSUE TITLE
Compilation errors in specific case study

### ISSUE THREAD

**Issue by jabiercoding** [lorilan/puck#1]
Apparently there are compilation issues with ArgoUML source code.
The version of ArgoUML is 0.28.1. I sent you the source code.
Thanks a lot!

**Comment by lorilan** [comment]
The issue seems to dwell in the underlying ExtendJ compiler. I forwarded the issue : https://bitbucket.org/extendj/extendj/issues/168/generic-method-lookup-error

**Comment by lorilan** [comment]
It has been promoted to its own issue : 
https://bitbucket.org/extendj/extendj/issues/169/generic-method-lookup-with-raw-typed

**Comment by lorilan** [comment]
It has been fixed, the argouml dependency graph can be build.
