### ISSUE TITLE
Enhancement: export dependencies

### ISSUE THREAD

**Issue by jabiercoding** [lorilan/puck#2]
It is very difficult to find a dependency graph generator which is scalable and that takes into account all the kind of dependencies supported by Pluck. Despite that it is not the main objective of the tool, it will be nice to have the option to dump or export some data about the nodes and the edges such as id, node kind, name, qualified name, edge kind etc.
Regarding the format, comma separated values (csv) will be enough, maybe in two separated files, one for nodes and another for edges.
This will allow to use these data to create other visualisations or to perform other analyses. I think that it can give value to this nice functionality of the tool.

**Comment by lorilan** [comment]
The export code is written (we may have to view together the exact syntax you want). 
However there are  some issues in the graph building that prevent me to to test this export on real study cases.

**Comment by jabiercoding** [comment]
Nice. Regarding the syntax, what about something like this?
For the `nodes.csv`

```
id;type;name;qualifiedName
13;Package;library;library
16;Interface;Item;library.Item
35;Class;Book;library.Book
46;Method;setTitle;library.Book.setTitle : : (String) -> void
```

For the `edges.csv`
Parent edgeType for reproducing the tree. And others with all the info about super type, sub type, client, providers, users and used.

```
source;target;edgeType
46;35;Parent
35;16;SuperType
```

This is a small java project maybe for testing this
[Library.zip](https://github.com/lorilan/puck/files/203047/Library.zip)

**Comment by lorilan** [comment]
It 's almost what I had done : I forgot the unqualified name ^_^
I added a type column, the qualified name does not include the return type so here is what you'll got got in the nodes.csv:

    id;type;name;qualifiedName; type
    13;Package;library;library;
    16;Interface;Item;library.Item;
    35;Class;Book;library.Book;
    46;Method;setTitle;library.Book.setTitle(String); (String) -> void

For the edges, for consistency with our naming, I uses the label "uses", "contains" and "isa" : 

    source;target;label
    35;46;Contains   //source is the parent and target is the child !
    35;16;Isa

You can find the printer code here : 
https://github.com/lorilan/puck/blob/dev/puckCore/src/main/scala/puck/graph/io/CSVPrinter.scala

I'm still having problem building graph for big project like argouml however it's working for the draw product line example you mailed me. You can download the current release here : 
http://puck.lip6.fr/puck-distrib-2016-04-05-155327.tgz

cheers !

**Comment by jabiercoding** [comment]
Great!
