### ISSUE TITLE
Minor issue, CSVPrinter, remove tabs \t

### ISSUE THREAD

**Issue by but4reuse** [lorilan/puck#6]
In CSVPrinter
puck/puckCore/src/main/scala/puck/graph/io/CSVPrinter.scala
there are many \t to include tabs, maybe for a better visualisation when a human open the file, however, they are not useful when programmatically accessing it. We have to do .trim() ;)
I did not know it but apparently RFC 4180  "Common Format and MIME Type for Comma-Separated Values (CSV) Files" states "Spaces are considered part of a field and should not be ignored." ;-)

**Comment by lorilan** [comment]
fixed in 92e1f93988d57fd2b396b9c79484e9acb20c7be9

**Comment by but4reuse** [comment]
@Seikishiki , with this new version of puck we should remove the .trim() in importCSV(URI uri)
In some cases, when importing a CSV, a tab or other whitespaces can be important characters.
